name: A test

on:
  push:

env:
  REPO_DIR: nipy

jobs:
  build:
    name: ${{ matrix.python }}
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        python: [
          "3.10",
          "3.11",
          "3.12",
        ]
    env:
      MB_PYTHON_VERSION: ${{ matrix.python }}
      BUILD_BASE: "meson-python>=0.13 cython>=3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Is Tomli installed?
        run: |
          python3 -c 'import tomli'
